/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyserRouteImport } from './routes/analyser'
import { Route as CopilotRouteImport } from './routes/copilot'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyserRoute = AnalyserRouteImport.update({
  id: '/analyser',
  path: '/analyser',
  getParentRoute: () => rootRouteImport,
} as any)
const CopilotRoute = CopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyser': typeof AnalyserRoute
  '/copilot': typeof CopilotRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyser': typeof AnalyserRoute
  '/copilot': typeof CopilotRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analyser': typeof AnalyserRoute
  '/copilot': typeof CopilotRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/analyser' | '/copilot'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/analyser' | '/copilot'
  id: '__root__' | '/' | '/analyser' | '/copilot'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyserRoute: typeof AnalyserRoute
  CopilotRoute: typeof CopilotRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyser': {
      id: '/analyser'
      path: '/analyser'
      fullPath: '/analyser'
      preLoaderRoute: typeof AnalyserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copilot': {
      id: '/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof CopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyserRoute: AnalyserRoute,
  CopilotRoute: CopilotRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
